# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/logplugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/logplugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/logplugin.proto\x12\x05proto\"M\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06module\x18\x04 \x01(\t\"\x7f\n\x0eSegmentRequest\x12\x12\n\nsegment_id\x18\x01 \x01(\x05\x12\x14\n\x0csegment_type\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\t\x12\x1d\n\x04logs\x18\x05 \x03(\x0b\x32\x0f.proto.LogEntry\"\xbb\x01\n\x0fSegmentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x04logs\x18\x03 \x03(\x0b\x32\x0f.proto.LogEntry\x12\x36\n\x08metadata\x18\x04 \x03(\x0b\x32$.proto.SegmentResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32P\n\rPluginService\x12?\n\x0eProcessSegment\x12\x15.proto.SegmentRequest\x1a\x16.proto.SegmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.logplugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=32
  _globals['_LOGENTRY']._serialized_end=109
  _globals['_SEGMENTREQUEST']._serialized_start=111
  _globals['_SEGMENTREQUEST']._serialized_end=238
  _globals['_SEGMENTRESPONSE']._serialized_start=241
  _globals['_SEGMENTRESPONSE']._serialized_end=428
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_start=381
  _globals['_SEGMENTRESPONSE_METADATAENTRY']._serialized_end=428
  _globals['_PLUGINSERVICE']._serialized_start=430
  _globals['_PLUGINSERVICE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
